import type { RidingArea } from '../types';
import { COTREX, editorial, official, reported } from './sources';

/**
 * Colorado Front Range / I-70 corridor seed data.
 *
 * Every number here has a source. Where no trustworthy number was found the
 * field is null and the app shows "Not enough data". Trailhead coordinates are
 * approximate (used for weather and routing, not for navigation — navigation hands
 * off to Maps by trailhead name).
 */

const JEFFCO_DESIGNATED_USE = 'https://www.jeffco.us/3817/Designated-Use';

export const frontRangeAreas: RidingArea[] = [
  {
    id: 'buffalo-creek',
    name: 'Buffalo Creek',
    region: 'colorado',
    subregion: 'Foothills South',
    manager: 'USDA Forest Service — Pike National Forest',
    trailhead: { name: 'Little Scraggy Trailhead', lat: 39.3525, lon: -105.2541, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['blue', 'black'],
    character: { technical: 1, climbing: 2, descending: 2, flow: 4, chunk: 1, exposure: 1, roots: 0, rock: 2, jumps: null, drops: 1, hikeABike: 0 },
    characterSource: editorial(),
    drainage: 'fast',
    drainageNote: 'Decomposed granite sheds water quickly — often rideable soon after rain, but gets loose and sandy when dry.',
    summary: 'Flowy, fast decomposed-granite singletrack in Pike National Forest, including Colorado Trail Segment 3. More XC/trail than chunk.',
    tags: ['flow', 'xc', 'colorado-trail', 'big-miles'],
    scenic: true,
    rides: [
      {
        id: 'bc-gashouse-sandy-wash',
        name: 'Gashouse → Miller Gulch → Homestead → Sandy Wash',
        distanceMi: null,
        gainFt: null,
        difficulty: 'blue',
        source: reported('MTB Project — Buffalo Creek Big Loop', 'https://www.mtbproject.com/trail/845269/buffalo-creek-big-loop-imba-epic'),
        notes: 'Many loop combinations are possible; check the route on MTB Project or Trailforks for current mileage.',
      },
    ],
    access: [
      { kind: 'advisory', summary: 'Colorado Trail Segment 3 is shared with hikers and bikepackers — heavy traffic on weekends.', source: official('USFS — Little Scraggy Trailhead', 'https://www.fs.usda.gov/r02/psicc/recreation/trails/colorado-trail-1776-segment-3-little-scraggy-trailhead') },
    ],
    parking: {
      primary: 'Little Scraggy Trailhead (east side of the recreation area)',
      fee: 'Day-use fee at Little Scraggy — amounts reported vary, check USFS',
      hours: null,
      overflow: 'Miller Gulch Trailhead (west side) is an alternate start',
      restrictions: null,
      restrooms: true,
      amenities: ['Restroom at Little Scraggy only'],
      availability: null,
      source: reported('USFS / rider reports via search, 2026', 'https://www.fs.usda.gov/r02/psicc/recreation/trails/colorado-trail-1776-segment-3-little-scraggy-trailhead'),
    },
    links: {
      official: 'https://www.fs.usda.gov/r02/psicc/recreation/trails/colorado-trail-1776-segment-3-little-scraggy-trailhead',
      officialLabel: 'USFS — Pike-San Isabel NF',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/buffalo-creek/',
      conditions: null,
    },
    apresHub: { name: 'Conifer', lat: 39.5211, lon: -105.305 },
  },
  {
    id: 'apex',
    name: 'Apex Park',
    region: 'colorado',
    subregion: 'Golden',
    manager: 'Jefferson County Open Space',
    trailhead: { name: 'Apex Park Trailhead, Golden', lat: 39.7156, lon: -105.2079, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['blue', 'black'],
    character: { technical: 3, climbing: 3, descending: 3, flow: 1, chunk: 3, exposure: 2, roots: 0, rock: 3, jumps: null, drops: 2, hikeABike: 1 },
    characterSource: editorial(),
    drainage: 'moderate',
    drainageNote: 'Rocky foothills soil — the rock sections dry quickly but the dirt between them holds moisture.',
    summary: 'Steep, rocky, technical foothills riding right above Golden. Heavy use, and designated-use rules vary by date.',
    tags: ['technical', 'rocky', 'close-in'],
    scenic: false,
    rides: [
      {
        id: 'apex-park-tour',
        name: 'Apex Park Tour',
        distanceMi: 8,
        gainFt: 1628,
        highPointFt: 7328,
        difficulty: 'black',
        source: reported('MTB Project — Apex Park Tour', 'https://www.mtbproject.com/trail/7000620/apex-park-tour'),
      },
    ],
    access: [
      {
        kind: 'oddEvenDates',
        bikesOn: 'even',
        summary: 'Designated-use trails (incl. Enchanted Forest & Magic Mountain): bikes only on even calendar dates, hikers/equestrians only on odd dates. Other Apex trails stay multi-use.',
        source: official('Jeffco Open Space — Designated Use', JEFFCO_DESIGNATED_USE),
      },
    ],
    parking: {
      primary: 'Apex Park Trailhead (off Heritage Rd, Golden)',
      fee: 'Free',
      hours: null,
      overflow: null,
      restrictions: null,
      restrooms: true,
      amenities: ['Restrooms', 'Bike pump', 'Map boards'],
      availability: null,
      source: reported('Visit Golden / trailhead listings', 'https://www.visitgolden.com/listing/apex-park/3933/'),
    },
    links: {
      official: 'https://www.jeffco.us/1190/Apex-Park',
      officialLabel: 'Jeffco Open Space — Apex Park',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/apex-park-16240/',
      conditions: JEFFCO_DESIGNATED_USE,
    },
    apresHub: { name: 'Golden', lat: 39.7555, lon: -105.2211 },
  },
  {
    id: 'white-ranch',
    name: 'White Ranch Park',
    region: 'colorado',
    subregion: 'Golden',
    manager: 'Jefferson County Open Space',
    trailhead: { name: 'White Ranch Park East Trailhead', lat: 39.797, lon: -105.2475, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['blue', 'black'],
    character: { technical: 3, climbing: 4, descending: 3, flow: 1, chunk: 3, exposure: 1, roots: 0, rock: 3, jumps: null, drops: 1, hikeABike: 2 },
    characterSource: editorial(),
    drainage: 'moderate',
    drainageNote: 'Loose, rocky foothills soil. Belcher Hill is steep and gets greasy when wet.',
    summary: 'A big, sustained climb up Belcher Hill, then loose, rocky descents. Most of the elevation comes in the first few miles.',
    tags: ['climbing', 'rocky', 'close-in'],
    scenic: true,
    rides: [
      {
        id: 'wr-belcher-longhorn',
        name: 'Belcher Hill → Maverick → Longhorn loop',
        distanceMi: 7.5,
        gainFt: 1538,
        difficulty: 'black',
        source: reported('AllTrails — Belcher Hill, Maverick, Longhorn Loop', 'https://www.alltrails.com/trail/us/colorado/belcher-hill-maverick-trail-longhorn-trail-loop'),
      },
    ],
    access: [
      { kind: 'advisory', summary: 'A 0.9 mi segment of Longhorn is bike-only and one-way (Jeffco designated-use pilot).', source: official('Jeffco Open Space — Designated Use', JEFFCO_DESIGNATED_USE) },
    ],
    parking: {
      primary: 'East Trailhead at W. 56th Ave',
      fee: 'Free',
      hours: null,
      overflow: 'West Trailhead on Belcher Hill Rd (top of the park)',
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: null,
      source: reported('CMC / trail listings', 'https://www.cmc.org/education-adventure/trips/routes-places/white-ranch-park'),
    },
    links: {
      official: 'https://www.jeffco.us/1437/White-Ranch-Park',
      officialLabel: 'Jeffco Open Space — White Ranch',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/white-ranch-park/',
      conditions: JEFFCO_DESIGNATED_USE,
    },
    apresHub: { name: 'Golden', lat: 39.7555, lon: -105.2211 },
  },
  {
    id: 'green-mountain',
    name: 'Green Mountain',
    region: 'colorado',
    subregion: 'Lakewood',
    manager: 'City of Lakewood — William F. Hayden Park',
    trailhead: { name: 'Green Mountain Trailhead, Alameda Pkwy, Lakewood', lat: 39.6935, lon: -105.176, approximate: true },
    trailheadElevationFt: 6080,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['green', 'blue'],
    character: { technical: 1, climbing: 2, descending: 2, flow: 2, chunk: 2, exposure: 0, roots: 0, rock: 2, jumps: 0, drops: 0, hikeABike: 0 },
    characterSource: editorial(),
    drainage: 'slow',
    drainageNote: 'Clay-heavy grassland soil. It turns to peanut butter after rain and is slow to dry. Please stay off it when wet.',
    summary: 'Open grassland loops close to town with big city views. Good for a quick after-work lap.',
    tags: ['quick', 'close-in', 'views', 'beginner-friendly'],
    scenic: true,
    rides: [
      {
        id: 'gm-hayden',
        name: 'Green Mountain & Hayden loop',
        distanceMi: 5,
        gainFt: 836,
        difficulty: 'green',
        source: reported('AllTrails — Green Mountain via Green Mountain and Hayden Trail', 'https://www.alltrails.com/trail/us/colorado/green-mountain-via-green-mountain-and-hayden-trail-loop'),
      },
      {
        id: 'gm-box-o-rox',
        name: "Box O' Rox → Rooney → Hayden → Green Mountain loop",
        distanceMi: 10.8,
        gainFt: 1683,
        difficulty: 'blue',
        source: reported('AllTrails — William F Hayden Green Mountain Park', 'https://www.alltrails.com/parks/us/colorado/william-f-hayden-green-mountain-park/mountain-biking'),
      },
    ],
    access: [],
    parking: {
      primary: 'Alameda Parkway trailheads',
      fee: 'Free',
      hours: null,
      overflow: 'Rooney Rd and other park trailheads',
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: null,
      source: reported('Trail guides via search, 2026', 'https://www.livingingreenmountain.com/blog/best-trails-green-mountain-lakewood'),
    },
    links: {
      official: 'https://www.lakewood.org/Search-Results?searchPhrase=William%20F%20Hayden%20Green%20Mountain',
      officialLabel: 'City of Lakewood (search)',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/green-mountain/',
      conditions: null,
    },
    apresHub: { name: 'Morrison', lat: 39.6536, lon: -105.1911 },
  },
  {
    id: 'hall-ranch',
    name: 'Hall Ranch',
    region: 'colorado',
    subregion: 'Lyons',
    manager: 'Boulder County Parks & Open Space',
    trailhead: { name: 'Hall Ranch Trailhead, Lyons', lat: 40.2107, lon: -105.2885, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['blue', 'black'],
    character: { technical: 2, climbing: 3, descending: 3, flow: 2, chunk: 3, exposure: 1, roots: 0, rock: 3, jumps: null, drops: 1, hikeABike: 0 },
    characterSource: editorial(),
    drainage: 'moderate',
    drainageNote: 'Rocky sandstone lower down, dirt up high. The upper Nelson Loop holds moisture longer.',
    summary: 'A rocky Bitterbrush climb up to the rolling Nelson Loop, then a fast, chunky descent back to Lyons.',
    tags: ['rocky', 'climbing', 'lyons', 'brewery-town'],
    scenic: true,
    rides: [
      {
        id: 'hr-bitterbrush-nelson',
        name: 'Bitterbrush + Nelson Loop',
        distanceMi: 9.9,
        gainFt: 1528,
        difficulty: 'blue',
        source: reported('AllTrails — Hall Ranch, Bitterbrush and Nelson Loop', 'https://www.alltrails.com/trail/us/colorado/hall-ranch-bitterbrush-and-nelson-loop-trail'),
      },
    ],
    access: [
      { kind: 'advisory', summary: 'Nighthawk Trail is hiker-only.', source: reported('MTB Project — Hall Ranch', 'https://www.mtbproject.com/trail/7047752/hall-ranch-intermediate-loop') },
    ],
    parking: {
      primary: 'Hall Ranch (Bitterbrush) Trailhead on Hwy 7',
      fee: null,
      hours: null,
      overflow: 'Many riders park in town in Lyons and ride to the trailhead',
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: 'Reported as often full, even on weekdays',
      source: reported('MTB Project rider notes', 'https://www.mtbproject.com/trail/7047752/hall-ranch-intermediate-loop'),
    },
    links: {
      official: 'https://bouldercounty.gov/open-space/parks-and-trails/hall-ranch/',
      officialLabel: 'Boulder County — Hall Ranch',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/hall-ranch-15771/',
      conditions: 'https://bouldercounty.gov/open-space/parks-and-trails/hall-ranch/',
    },
    apresHub: { name: 'Lyons', lat: 40.2247, lon: -105.2714 },
  },
  {
    id: 'heil-valley',
    name: 'Heil Valley Ranch',
    region: 'colorado',
    subregion: 'Lyons',
    manager: 'Boulder County Parks & Open Space',
    trailhead: { name: 'Heil Valley Ranch Trailhead, Geer Canyon Dr', lat: 40.1487, lon: -105.3003, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['blue', 'blue'],
    character: { technical: 2, climbing: 2, descending: 2, flow: 2, chunk: 2, exposure: 0, roots: 0, rock: 2, jumps: null, drops: null, hikeABike: 0 },
    characterSource: editorial(),
    drainage: 'moderate',
    drainageNote: 'Mix of rocky tread (Wapiti) and forest dirt (Wild Turkey/Ponderosa).',
    summary: 'Rocky Wapiti climb to a set of forested loops. Can link to Picture Rock and descend into Lyons.',
    tags: ['forest', 'lyons', 'brewery-town'],
    scenic: true,
    rides: [
      {
        id: 'hv-wapiti-ponderosa-turkey',
        name: 'Wapiti → Ponderosa → Wild Turkey',
        distanceMi: null,
        gainFt: null,
        difficulty: 'blue',
        source: reported('MTB Project — Heil Ranch', 'https://www.mtbproject.com/trail/52119/heil-ranch'),
        notes: 'Reported segment figures: Wapiti 2.5 mi / 822′ gain, Ponderosa Loop 2.6 mi, Wild Turkey 2.9 mi. The total depends on how you link them.',
      },
    ],
    access: [],
    parking: {
      primary: 'Heil Valley Ranch Trailhead (Geer Canyon Dr)',
      fee: null,
      hours: null,
      overflow: 'Picture Rock Trailhead in Lyons is an alternate start',
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: null,
      source: reported('10Adventures — Heil Valley Ranch', 'https://www.10adventures.com/mountain-biking/boulder/heil-valley-ranch-mtb/'),
    },
    links: {
      official: 'https://bouldercounty.gov/open-space/parks-and-trails/heil-valley-ranch/',
      officialLabel: 'Boulder County — Heil Valley Ranch',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/heil-valley-ranch-15770/',
      conditions: 'https://bouldercounty.gov/open-space/parks-and-trails/heil-valley-ranch/',
    },
    apresHub: { name: 'Lyons', lat: 40.2247, lon: -105.2714 },
  },
  {
    id: 'betasso',
    name: 'Betasso Preserve',
    region: 'colorado',
    subregion: 'Boulder',
    manager: 'Boulder County Parks & Open Space',
    trailhead: { name: 'Betasso Preserve Trailhead, Boulder', lat: 40.0167, lon: -105.3444, approximate: true },
    trailheadElevationFt: null,
    networkMiles: 6.5,
    networkMilesSource: reported('Boulder County trail lengths (Canyon 3.3 + Benjamin 2.4 + Link 0.8)', 'https://bouldercounty.gov/open-space/parks-and-trails/betasso-preserve/'),
    trailCount: 3,
    difficultyRange: ['blue', 'blue'],
    character: { technical: 1, climbing: 2, descending: 2, flow: 3, chunk: 1, exposure: 0, roots: 0, rock: 1, jumps: 0, drops: 0, hikeABike: 0 },
    characterSource: editorial(),
    drainage: 'fast',
    drainageNote: 'Granitic soil drains well. One of the first Boulder spots to dry out.',
    summary: 'Buffed, flowy loops in a ponderosa forest just up Boulder Canyon. Direction alternates on a posted schedule.',
    tags: ['flow', 'quick', 'boulder'],
    scenic: true,
    rides: [
      {
        id: 'betasso-canyon-benjamin',
        name: 'Canyon Loop + Benjamin Loop',
        distanceMi: 7.3,
        gainFt: null,
        difficulty: 'blue',
        source: reported('Boulder County — Betasso Preserve (via search)', 'https://bouldercounty.gov/open-space/parks-and-trails/betasso-preserve/'),
      },
    ],
    access: [
      {
        kind: 'closedWeekdays',
        days: [3, 6],
        summary: 'Closed to bikes on Wednesdays and Saturdays.',
        source: official('Boulder County — Betasso Preserve', 'https://bouldercounty.gov/open-space/parks-and-trails/betasso-preserve/'),
      },
      {
        kind: 'advisory',
        summary: 'Bikes must ride Canyon and Benjamin loops in the posted direction, which changes on a schedule.',
        source: official('Boulder County — Betasso Preserve', 'https://bouldercounty.gov/open-space/parks-and-trails/betasso-preserve/'),
      },
    ],
    parking: {
      primary: 'Betasso Preserve trailhead',
      fee: null,
      hours: null,
      overflow: null,
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: null,
      source: null,
    },
    links: {
      official: 'https://bouldercounty.gov/open-space/parks-and-trails/betasso-preserve/',
      officialLabel: 'Boulder County — Betasso Preserve',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/betasso-preserve/',
      conditions: 'https://bouldercounty.gov/open-space/parks-and-trails/betasso-preserve/',
    },
    apresHub: { name: 'Boulder', lat: 40.015, lon: -105.2705 },
  },
  {
    id: 'walker-ranch',
    name: 'Walker Ranch',
    region: 'colorado',
    subregion: 'Boulder',
    manager: 'Boulder County Parks & Open Space',
    trailhead: { name: 'Walker Ranch Loop Trailhead, Flagstaff Rd', lat: 39.9513, lon: -105.3382, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['black', 'black'],
    character: { technical: 3, climbing: 3, descending: 3, flow: 1, chunk: 3, exposure: 2, roots: 0, rock: 3, jumps: 0, drops: 2, hikeABike: 3 },
    characterSource: editorial(),
    drainage: 'moderate',
    drainageNote: 'Loose granite on steep grades. Traction is poor both when it is wet and when it is bone dry.',
    summary: 'A classic, hard loop: fast, loose descents, steep climbs, and a mandatory hike-a-bike staircase down to South Boulder Creek.',
    tags: ['technical', 'hike-a-bike', 'classic'],
    scenic: true,
    rides: [
      {
        id: 'walker-loop',
        name: 'Walker Ranch Loop',
        distanceMi: 7.6,
        gainFt: 1559,
        difficulty: 'black',
        source: reported('Trailforks — Walker Ranch Loop', 'https://www.trailforks.com/trails/walker-ranch-loop/'),
      },
    ],
    access: [],
    parking: {
      primary: 'Walker Ranch Loop Trailhead on Flagstaff Rd',
      fee: null,
      hours: null,
      overflow: null,
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: 'Reported to fill quickly on weekends',
      source: reported('10Adventures — Walker Ranch Loop', 'https://www.10adventures.com/mountain-biking/boulder/walker-ranch-loop-mtb/'),
    },
    links: {
      official: 'https://bouldercounty.gov/open-space/parks-and-trails/walker-ranch/',
      officialLabel: 'Boulder County — Walker Ranch',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/route/walker-ranch-loop/',
      conditions: 'https://bouldercounty.gov/open-space/parks-and-trails/walker-ranch/',
    },
    apresHub: { name: 'Boulder', lat: 40.015, lon: -105.2705 },
  },
  {
    id: 'marshall-mesa',
    name: 'Marshall Mesa',
    region: 'colorado',
    subregion: 'Boulder',
    manager: 'City of Boulder Open Space & Mountain Parks',
    trailhead: { name: 'Marshall Mesa Trailhead, Boulder', lat: 39.9537, lon: -105.2306, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['green', 'blue'],
    character: { technical: 1, climbing: 1, descending: 1, flow: 2, chunk: 1, exposure: 0, roots: 0, rock: 1, jumps: 0, drops: 0, hikeABike: 0 },
    characterSource: editorial(),
    drainage: 'slow',
    drainageNote: 'Prairie clay. It stays muddy long after storms and ruts badly if you ride it wet.',
    summary: 'Mellow mesa and prairie singletrack with Flatirons views. Links to Community Ditch and Doudy Draw.',
    tags: ['mellow', 'views', 'beginner-friendly', 'boulder'],
    scenic: true,
    rides: [
      {
        id: 'mm-community-ditch-doudy',
        name: 'Community Ditch → Doudy Draw → Spring Brook loop',
        distanceMi: 11.4,
        gainFt: 826,
        difficulty: 'blue',
        source: reported('AllTrails — Community Ditch to Doudy Draw and Spring Brook Loop', 'https://www.alltrails.com/trail/us/colorado/community-ditch-to-doudy-draw-and-spring-brook-loop-to-marshall-mesa'),
      },
    ],
    access: [
      { kind: 'advisory', summary: 'Marshall Mesa Trail itself does not allow bikes. Nearby Marshall Valley, Coal Seam, Community Ditch and others do.', source: official('City of Boulder OSMP — Marshall Mesa', 'https://bouldercolorado.gov/trail/marshall-mesa') },
      { kind: 'advisory', summary: 'Trailhead access was reported temporarily changed in 2025. Check OSMP before you drive.', source: official('City of Boulder OSMP — Marshall Mesa Trailhead', 'https://bouldercolorado.gov/trailhead/marshall-mesa') },
    ],
    parking: {
      primary: 'Marshall Mesa Trailhead',
      fee: '$5 for vehicles not registered in Boulder County (OSMP fee lot; annual permits available)',
      hours: null,
      overflow: null,
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: null,
      source: official('City of Boulder — OSMP Parking Permits and Fees', 'https://bouldercolorado.gov/services/osmp-parking-permits-and-fees'),
    },
    links: {
      official: 'https://bouldercolorado.gov/trailhead/marshall-mesa',
      officialLabel: 'City of Boulder OSMP — Marshall Mesa',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/route/marshall-mesa-doudy-draw-loop/',
      conditions: 'https://bouldercolorado.gov/trailhead/marshall-mesa',
    },
    apresHub: { name: 'Boulder', lat: 40.015, lon: -105.2705 },
  },
  {
    id: 'north-table',
    name: 'North Table Mountain',
    region: 'colorado',
    subregion: 'Golden',
    manager: 'Jefferson County Open Space',
    trailhead: { name: 'North Table Mountain Park West Trailhead, Golden', lat: 39.7768, lon: -105.2264, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['green', 'black'],
    character: { technical: 2, climbing: 2, descending: 2, flow: 2, chunk: 2, exposure: 1, roots: 0, rock: 2, jumps: null, drops: null, hikeABike: 0 },
    characterSource: editorial(),
    drainage: 'slow',
    drainageNote: 'Volcanic mesa with clay soils. The steep access road is fine, but the mesa-top dirt stays soft after rain.',
    summary: 'A steep access climb onto a lava-capped mesa, then a mix of easy loops and rocky black lines. Close to town.',
    tags: ['close-in', 'quick', 'views'],
    scenic: true,
    rides: [
      {
        id: 'ntm-outer',
        name: 'North Table outer loop',
        distanceMi: 7.5,
        gainFt: 1100,
        difficulty: 'blue',
        source: reported('The Outbound — North Table Mountain Loop', 'https://www.theoutbound.com/colorado/mountain-biking/mountain-bike-the-north-table-mountain-loop'),
      },
    ],
    access: [],
    parking: {
      primary: 'West Trailhead on State Highway 93',
      fee: 'Free',
      hours: null,
      overflow: null,
      restrictions: null,
      restrooms: true,
      amenities: ['Large paved lot', 'Restrooms', 'Water (reported)'],
      availability: null,
      source: reported('The Outbound / trail guides', 'https://www.theoutbound.com/colorado/mountain-biking/mountain-bike-the-north-table-mountain-loop'),
    },
    links: {
      official: 'https://www.jeffco.us/Search?searchPhrase=North%20Table%20Mountain%20Park',
      officialLabel: 'Jeffco Open Space (search)',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/north-table-mountain-park/',
      conditions: null,
    },
    apresHub: { name: 'Golden', lat: 39.7555, lon: -105.2211 },
  },
  {
    id: 'floyd-hill',
    name: 'Floyd Hill Open Space',
    region: 'colorado',
    subregion: 'I-70 Corridor',
    manager: 'Clear Creek County Open Space',
    trailhead: { name: 'Floyd Hill Open Space Trailhead, US-40', lat: 39.7236, lon: -105.4199, approximate: true },
    trailheadElevationFt: null,
    networkMiles: null,
    networkMilesSource: null,
    trailCount: null,
    difficultyRange: ['blue', 'dblack'],
    character: { technical: 2, climbing: 2, descending: 3, flow: 3, chunk: 2, exposure: 1, roots: 0, rock: 2, jumps: 2, drops: 2, hikeABike: 0 },
    characterSource: editorial(),
    drainage: 'moderate',
    drainageNote: 'Built trail on mountain soils. Most of it faces the sun and dries out moderately fast.',
    summary: 'Newer, purpose-built network just off I-70, featuring The Sluice: a bike-only downhill with black and double-black alternate lines.',
    tags: ['flow', 'gravity', 'i70', 'quick'],
    scenic: true,
    rides: [
      {
        id: 'fh-canyon-view',
        name: 'Canyon View Loop',
        distanceMi: 3.1,
        gainFt: 590,
        difficulty: 'blue',
        source: reported('Trailforks — Floyd Hill Open Space', 'https://www.trailforks.com/region/floyd-hill-open-space-25197/'),
      },
      {
        id: 'fh-sluice',
        name: 'The Sluice (downhill, bike-only)',
        distanceMi: 1.3,
        gainFt: null,
        difficulty: 'black',
        source: reported('The Colorado Sun — Floyd Hill one-way trail', 'https://coloradosun.com/2019/09/05/downhill-only-mountain-bike-trail-floyd-hill/'),
        notes: 'Drops about 700 vertical feet. The main line is blue/black; the alternate lines are black to double-black.',
      },
    ],
    access: [
      { kind: 'advisory', summary: 'The Sluice is bike-only and downhill-only.', source: reported('COMBA — Floyd Hill Open Space', 'https://www.comba.org/floyd-hill-open-space') },
    ],
    parking: {
      primary: 'Trailhead on US-40, just west of I-70 Exit 248',
      fee: 'No parking fee (reported)',
      hours: null,
      overflow: null,
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: null,
      source: reported('COMBA — Floyd Hill Open Space', 'https://www.comba.org/floyd-hill-open-space'),
    },
    links: {
      official: 'https://www.comba.org/floyd-hill-open-space',
      officialLabel: 'COMBA — Floyd Hill (trail steward)',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/floyd-hill-open-space-25197/',
      conditions: null,
    },
    apresHub: { name: 'Idaho Springs', lat: 39.7425, lon: -105.5136 },
  },
  {
    id: 'maryland-mountain',
    name: 'Maryland Mountain',
    region: 'colorado',
    subregion: 'I-70 Corridor',
    manager: 'City of Black Hawk — Quartz Valley Open Space Park',
    trailhead: { name: 'Hidden Treasure Trailhead, 8060 Black Hawk Blvd, Black Hawk', lat: 39.8055, lon: -105.4925, approximate: true },
    trailheadElevationFt: null,
    networkMiles: 16,
    networkMilesSource: official('City of Black Hawk — Maryland Mountain', 'https://www.cityofblackhawk.org/things-do-black-hawk/page/maryland-mountain-quartz-valley-open-space-park-hiking-biking'),
    trailCount: null,
    difficultyRange: ['blue', 'black'],
    character: { technical: 3, climbing: 3, descending: 3, flow: 2, chunk: 3, exposure: 1, roots: 0, rock: 3, jumps: 2, drops: 2, hikeABike: 1 },
    characterSource: editorial(),
    drainage: 'moderate',
    drainageNote: 'High elevation (~8,000 ft+). Snow lingers into spring and the season starts later than on the plains-edge trails.',
    summary: 'Old mining country above Black Hawk: rocky climbs, historic tramway grades, and downhill-only bike trails with optional jumps and drops.',
    tags: ['technical', 'gravity', 'high-elevation', 'i70'],
    scenic: true,
    rides: [
      {
        id: 'mm-tramway',
        name: 'Maryland Mountain via Historic Gilpin Tramway',
        distanceMi: 5.7,
        gainFt: 1017,
        difficulty: 'blue',
        source: reported('AllTrails — Maryland Mountain via Historic Gilpin Tramway', 'https://www.alltrails.com/trail/us/colorado/maryland-mountain-via-historic-gilpin-tramway'),
      },
    ],
    access: [
      { kind: 'advisory', summary: 'Includes 3 downhill-only, bike-only trails (e.g. Hard Money). Park hours: dawn to dusk.', source: official('City of Black Hawk — Maryland Mountain', 'https://www.cityofblackhawk.org/things-do-black-hawk/page/maryland-mountain-quartz-valley-open-space-park-hiking-biking') },
    ],
    parking: {
      primary: 'Hidden Treasure Trailhead, 8060 Black Hawk Blvd (bike/ped bridge over Hwy 119)',
      fee: null,
      hours: 'Dawn to dusk',
      overflow: 'Overflow lot about 0.25 mi south of Hidden Treasure',
      restrictions: null,
      restrooms: null,
      amenities: ['Bike/pedestrian bridge to the trail system'],
      availability: null,
      source: official('City of Black Hawk — Maryland Mountain', 'https://www.cityofblackhawk.org/things-do-black-hawk/page/maryland-mountain-quartz-valley-open-space-park-hiking-biking'),
    },
    links: {
      official: 'https://www.cityofblackhawk.org/things-do-black-hawk/page/maryland-mountain-quartz-valley-open-space-park-hiking-biking',
      officialLabel: 'City of Black Hawk — Maryland Mountain',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/maryland-mountain-quartz-valley-park/',
      conditions: null,
    },
    apresHub: { name: 'Idaho Springs', lat: 39.7425, lon: -105.5136 },
  },
  {
    id: 'staunton',
    name: 'Staunton State Park',
    region: 'colorado',
    subregion: 'Foothills South',
    manager: 'Colorado Parks & Wildlife',
    trailhead: { name: 'Staunton State Park, Pine', lat: 39.4997, lon: -105.379, approximate: true },
    trailheadElevationFt: null,
    networkMiles: 17,
    networkMilesSource: reported('5280 — Staunton State Park (bike-legal mileage)', 'https://5280.com/staunton-state-park/'),
    trailCount: null,
    difficultyRange: ['blue', 'black'],
    character: { technical: 2, climbing: 3, descending: 2, flow: 2, chunk: 2, exposure: 1, roots: 1, rock: 2, jumps: null, drops: null, hikeABike: 1 },
    characterSource: editorial(),
    drainage: 'fast',
    drainageNote: 'Granitic soils drain well, but the high point is over 9,500 ft, so snow can linger in the shoulder seasons.',
    summary: 'Big-mountain feel close to Denver: granite domes, aspen, and a full loop that tops out above 9,500 ft.',
    tags: ['big-miles', 'scenic', 'high-elevation', 'adventure'],
    scenic: true,
    rides: [
      {
        id: 'staunton-full-cw',
        name: 'Full Clockwise Loop',
        distanceMi: 19,
        gainFt: 2663,
        highPointFt: 9514,
        difficulty: 'blue',
        source: reported('MTB Project — Staunton State Park Full Clockwise Loop', 'https://www.mtbproject.com/trail/922946/staunton-state-park-full-clockwise-loop'),
      },
    ],
    access: [
      { kind: 'advisory', summary: 'State park: a CPW vehicle pass is required.', source: official('Colorado Parks & Wildlife — Staunton', 'https://cpw.state.co.us/state-parks/staunton-state-park') },
    ],
    parking: {
      primary: 'Main park lots (entrance station)',
      fee: 'CPW daily vehicle pass or annual state parks pass required',
      hours: null,
      overflow: 'Mason Creek lot (east side)',
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: null,
      source: official('Colorado Parks & Wildlife — Staunton', 'https://cpw.state.co.us/state-parks/staunton-state-park'),
    },
    links: {
      official: 'https://cpw.state.co.us/state-parks/staunton-state-park',
      officialLabel: 'CPW — Staunton State Park',
      officialMap: 'https://cpw.state.co.us/state-parks/staunton-state-park/staunton-state-park-activities-trails',
      trailMap: 'https://www.trailforks.com/region/staunton-state-park-15820/',
      conditions: 'https://cpw.state.co.us/state-parks/staunton-state-park',
    },
    apresHub: { name: 'Conifer', lat: 39.5211, lon: -105.305 },
  },
  {
    id: 'golden-gate',
    name: 'Golden Gate Canyon State Park',
    region: 'colorado',
    subregion: 'Foothills North',
    manager: 'Colorado Parks & Wildlife',
    trailhead: { name: 'Golden Gate Canyon State Park Visitor Center', lat: 39.8312, lon: -105.4116, approximate: true },
    trailheadElevationFt: null,
    networkMiles: 19,
    networkMilesSource: reported('Park descriptions — approx. multi-use (bike-legal) mileage', 'https://www.singletracks.com/bike-trails/golden-gate-canyon-state-park/'),
    trailCount: null,
    difficultyRange: ['blue', 'black'],
    character: { technical: 3, climbing: 3, descending: 3, flow: 1, chunk: 3, exposure: 1, roots: 1, rock: 3, jumps: null, drops: null, hikeABike: 2 },
    characterSource: editorial(),
    drainage: 'moderate',
    drainageNote: 'Forest and meadow trails with stream crossings. Shaded sections stay wet longer.',
    summary: 'Rugged, rocky backcountry-style riding with aspen and Continental Divide views from Panorama Point.',
    tags: ['scenic', 'adventure', 'rocky', 'aspens'],
    scenic: true,
    rides: [
      {
        id: 'ggc-mule-deer',
        name: 'Mule Deer Trail',
        distanceMi: 7.1,
        gainFt: 1317,
        difficulty: 'blue',
        source: reported('AllTrails — Golden Gate Canyon State Park mountain biking', 'https://www.alltrails.com/parks/us/colorado/golden-gate-canyon-state-park/mountain-biking'),
      },
    ],
    access: [
      { kind: 'advisory', summary: 'Bikes are allowed only on designated multi-use trails.', source: official('Colorado Parks & Wildlife — Golden Gate Canyon', 'https://cpw.state.co.us/state-parks/golden-gate-canyon-state-park') },
    ],
    parking: {
      primary: 'Visitor Center and trailhead lots throughout the park',
      fee: 'CPW daily vehicle pass or annual state parks pass required',
      hours: null,
      overflow: null,
      restrictions: null,
      restrooms: null,
      amenities: [],
      availability: null,
      source: official('Colorado Parks & Wildlife — Golden Gate Canyon', 'https://cpw.state.co.us/state-parks/golden-gate-canyon-state-park'),
    },
    links: {
      official: 'https://cpw.state.co.us/state-parks/golden-gate-canyon-state-park',
      officialLabel: 'CPW — Golden Gate Canyon State Park',
      officialMap: COTREX,
      trailMap: 'https://www.trailforks.com/region/golden-gate-canyon-state-park/',
      conditions: 'https://cpw.state.co.us/state-parks/golden-gate-canyon-state-park',
    },
    apresHub: { name: 'Golden', lat: 39.7555, lon: -105.2211 },
  },
];
